#
# NavQ+ Image Development Environment Base
#

FROM ubuntu:20.04
LABEL maintainer="Benjamin Perseghetti <bperseghetti@rudislabs.com>"

ENV DEBIAN_FRONTEND noninteractive
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

RUN apt-get update && apt-get -y --quiet --no-install-recommends install \
		bzip2 \
		ca-certificates \
		cmake \
		cppcheck \
		dirmngr \
		doxygen \
		file \
		g++ \
		gcc \
		gdb \
		git \
		gnupg \
		gosu \
		lcov \
		libfreetype6-dev \
		libgtest-dev \
		libpng-dev \
		libssl-dev \
		lsb-release \
		make \
		ninja-build \
		openjdk-8-jdk \
		openjdk-8-jre \
		openssh-client \
		pkg-config \
		python3-dev \
		python3-pip \
		rsync \
		shellcheck \
		tzdata \
		unzip \
		valgrind \
		wget \
		xsltproc \
		zip \
		gawk \
		git-core \
		diffstat \
		texinfo \
		gcc-multilib \
		build-essential \
		chrpath \
		socat \
		cpio \
		python3-pexpect \
		xz-utils \
		debianutils \
		iputils-ping \
		python3-git \
		python3-jinja2 \
		libegl1-mesa \
		libsdl1.2-dev \
		pylint3 \
		python3-subunit \
		mesa-common-dev \
		curl \
		zstd \
		liblz4-tool \
		bitbake \
	&& apt-get -y autoremove \
	&& apt-get clean autoclean \
	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# Install Python 3 pip build dependencies first.
RUN python3 -m pip install --upgrade pip wheel setuptools

# Install repo tool
RUN mkdir /home/$USER/bin \
	&& curl https://storage.googleapis.com/git-repo-downloads/repo > /home/$USER/bin/repo \
	&& chmod a+x /home/$USER/bin/repo

ENV PATH "/home/$USER/bin:$PATH"

RUN git config --global user.name 'User Name' \
	&& git config --global user.email 'user@name.com'

RUN set -x \
	&& BUILD=`date +%Y%m%d.%H%M`; start=`date +%s` \
	&& pwd \
	&& mkdir -p /home/$USER/yocto/build_515 \
	&& cd /home/$USER/yocto/build_515 \
	&& pwd \
	&& repo init -u https://source.codeaurora.org/external/imx/imx-manifest -b imx-linux-kirkstone -m imx-5.15.32-2.0.0_desktop.xml \
	&& repo sync \
	&& cd /home/$USER/yocto/build_515/sources \
	&& git clone https://github.com/rudislabs/NavQPlus.git -b lf5.15.32_2.0.0-ros2 meta-nxp-hovergames \
	&& cd /home/$USER/yocto/build_515 \
	&& DISTRO=imx-desktop-xwayland MACHINE=imx8mpnavq EULA=yes source ./imx-setup-desktop.sh -b build \
	&& cd /home/$USER/yocto/build_515/build/conf
	&& echo BBLAYERS += \"\${BSPDIR}/sources/meta-nxp-hovergames\" >> bblayers.conf \
	&& cd /home/$USER/yocto/build_515/build \
	&& bitbake imx-image-desktop \
	&& finish=`date +%s`; echo "### Build Time = `expr \( $finish - $start \) / 60` minutes" \
	&& set +x

# setup virtual X server
RUN mkdir /tmp/.X11-unix && \
	chmod 1777 /tmp/.X11-unix && \
	chown -R root:root /tmp/.X11-unix
ENV DISPLAY :99

ENV TERM=xterm
ENV TZ=UTC

# create and start as LOCAL_USER_ID
COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["/bin/bash"]
